server:
  port: 8084


message: Hello World!
# message: Goodbye... maybe!!!


scheduler:
  thread-name-prefix: kafkaProducerThread-
  poolSize: 5
  awaitTerminationSeconds: 9
  daemon: true

notification:
  type: sms
  
spring:
  application:
    baseUrl: 'http://localhost:{port}/actuator/refresh'
    
