server:
  port: 8084


# message: Hello World!
message: Goodbye... maybe!!!


scheduler:
  thread-name-prefix: kafkaProducerThread-
  poolSize: 51
  awaitTerminationSeconds: 19
  daemon: true

notification:
  type: email
  # type: sms
  
spring:
  application:
    baseUrl: 'http://localhost:{port}/actuator/refresh'
    
