server:
  port: 8773

spring:
  cloud:
    config:
      server:
        git:
          uri: https://$GIT_USERNAME:$GIT_PASSWORD@github.com/Orisakwe-Nwokocha/Central-Config.git
          default-label: master
          ignoreLocalSshSettings: true
