server:
  port: 8773

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Orisakwe-Nwokocha/Central-Config.git
          default-label: master
          ignoreLocalSshSettings: true
#          username: ${GIT_USERNAME}
#          password: ${GIT_PASSWORD}

