server:
  port: 8773

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Orisakwe-Nwokocha/Central-Config.git/config
          clone-on-start: true
          default-label: master
